"""Every knob this project has, declared once.

There were thirty-two scattered `os.environ.get` calls before this, and three
of them disagreed with each other about the default: the loop wrote short
replies in one hand while the tool that previews the hand drew another, and
the notebook the consent gate named was not the notebook the loop announced.
A default that appears twice will eventually appear twice differently.

Two other things follow from putting them in one place. `.env` is read here,
in Python, so a tool picks up the same configuration the launcher does --
before, only the shell scripts sourced it and running a tool directly got
bare defaults. And `.env.example` is *generated* from these declarations
rather than maintained by hand, which is why every line in it is commented
out: a template cannot disagree with a default it does not set.

Precedence is the usual one: a variable already in the environment beats
`.env`, so `RM2_SSH_HOST=rm2 riddle device build` works for a one-off. That
inverts what `set -a; source .env` used to do, so `riddle config` prints
where each value came from.
"""

import os
from dataclasses import dataclass, fields
from pathlib import Path
from typing import Any, Callable

from riddle import paths

# --- the declaration ----------------------------------------------------


@dataclass(frozen=True)
class Setting:
    name: str                       # RIDDLE_PAUSE_MS
    attr: str                       # pause_ms
    kind: type                      # str | int | float | bool | Path
    default: Any                    # None when derived
    section: str
    help: str
    derive: Callable[["Config"], Any] | None = None
    base: str = "root"              # for Path settings: root | var | models
    secret: bool = False            # never printed
    manual: bool = False            # documented, read by no code here


SETTINGS: tuple[Setting, ...] = (
    # --- device access ---
    Setting("RM2_HOST", "rm2_host", str, "10.11.99.1", "device",
            "The address every reMarkable exposes with USB web interface on. "
            "For logging in by hand; the code uses RM2_SSH_HOST.", manual=True),
    Setting("RM2_USER", "rm2_user", str, "root", "device",
            "For logging in by hand.", manual=True),
    Setting("RM2_PASSWORD", "rm2_password", str, "", "device",
            "Printed on the tablet under Settings > Help > Copyrights and "
            "licenses, and regenerated by major firmware updates. For logging "
            "in by hand; nothing here reads it.", secret=True, manual=True),
    Setting("RM2_SSH_HOST", "ssh_host", str, "rm2", "device",
            "The ssh alias the diary talks to. Define it in ~/.ssh/config, "
            "ideally with a key, so no password is ever needed."),
    Setting("RM2_WIFI_HOST", "wifi_host", str, "", "device",
            "The tablet's address over wifi, if it has one. Only `riddle "
            "link` uses it, to probe both routes."),
    Setting("RIDDLE_AGENT", "agent", str, "/home/root/riddle/riddled", "device",
            "Where the agent lives on the tablet."),

    # --- the diary ---
    Setting("RIDDLE_NOTEBOOK", "notebook", str, "Notebook", "diary",
            "Which notebook to announce at startup. Ink lands in whatever "
            "page is actually on screen; this is a statement of intent."),
    Setting("RIDDLE_PAUSE_MS", "pause_ms", int, 3000, "diary",
            "Idle time after a pen lift before the diary answers."),
    Setting("RIDDLE_OPENAI_MODEL", "openai_model", str, "gpt-4.1-mini", "diary",
            "Which model answers. It has to be able to see -- the page is "
            "attached to the turn -- and it has to be quick, because the "
            "reply is two dozen words and the pause is already over."),
    Setting("RIDDLE_OPENAI_KEY", "openai_key", str, "", "diary",
            "The OpenAI API key. Put it in .env, which is gitignored and "
            "must be chmod 600.", secret=True),
    Setting("RIDDLE_OPENAI_URL", "openai_url", str, "https://api.openai.com/v1",
            "diary",
            "Where that API lives. Anything OpenAI-compatible that takes an "
            "image works, which is how a local model would be dropped in."),
    Setting("RIDDLE_MAX_WORDS", "max_words", int, 22, "diary",
            "How long a reply may be. A page is small and the pen is slow."),

    # --- the hand ---
    Setting("RIDDLE_FONT_BODY", "font_body", str, "futural", "hand",
            "The hand for longer replies. A .jhf in the fonts directory is "
            "Hershey; a .ttf is skeletonised into a joined hand."),
    Setting("RIDDLE_FONT_ACCENT", "font_accent", str, "DancingScript", "hand",
            "The hand for short replies and *emphasis* runs."),
    Setting("RIDDLE_INK_HEIGHT", "ink_height", int, 72, "hand",
            "Cap height of the diary's writing, in screen pixels."),
    Setting("RIDDLE_PRESSURE", "pressure", int, 3200, "hand",
            "How hard the injected nib presses, 0-4095. Thicker ink, and "
            "xochitl is likelier to believe it."),

    # --- the page you speak into ---
    Setting("RIDDLE_DB", "db", Path, "riddle.db", "voice",
            "The store both halves write. Relative paths hang off var/.",
            base="var"),
    Setting("RIDDLE_WEB_HOST", "web_host", str, "127.0.0.1", "voice",
            "Loopback on purpose: `riddle voice share` is what exposes it, "
            "and it does so behind a real certificate."),
    Setting("RIDDLE_WEB_PORT", "web_port", int, 8765, "voice",
            "The port the page is served on."),
    Setting("RIDDLE_WEB_DIR", "web_dir", Path, "apps/web/dist", "voice",
            "The built client. Without it the server serves a stub page and "
            "the api still works.", base="root"),
    Setting("RIDDLE_WEB_DEBUG", "web_debug", bool, False, "voice",
            "Log every request line."),
    Setting("RIDDLE_WEB_PASSWORD", "web_password", str, "", "voice",
            "One password in front of the page. Empty means no gate, which is "
            "right on loopback and wrong the moment the port is published.",
            secret=True),
    Setting("RIDDLE_ASR_MODEL", "asr_model", Path,
            "ggml-parakeet-tdt-0.6b-v3-q8_0.bin", "voice",
            "The speech model, fetched once by hand. Relative paths hang off "
            "var/models.", base="models"),
    Setting("RIDDLE_ASR_THREADS", "asr_threads", int, 4, "voice",
            "Threads for one parakeet run. Runs are serialised anyway: two "
            "of them share one Metal context and make each other slower."),
    Setting("RIDDLE_VAD_FLOOR", "vad_floor", float, 0.012, "voice",
            "The quietest thing the gate will call speech. Too low and the "
            "fridge is transcribed; too high and quiet speech is lost."),
    Setting("RIDDLE_VAD_HANG_MS", "vad_hang_ms", int, 700, "voice",
            "Silence before an utterance is considered finished. Too short "
            "and sentences are cut mid-clause."),
    Setting("RIDDLE_VAD_MAX_MS", "vad_max_ms", int, 20000, "voice",
            "Forced cut. Somebody is monologuing."),
    Setting("RIDDLE_AUDIO_KEEP_DAYS", "audio_keep_days", int, 7, "voice",
            "How long recordings of your room stay on disk. 0 keeps them "
            "forever, which is a decision worth making on purpose."),

    # --- the client's build ---
    Setting("RIDDLE_SERVER", "server", str, None, "web",
            "Where the dev server proxies /api and /ws. Derived from the "
            "host and port unless you set it.",
            derive=lambda c: f"http://{c.web_host}:{c.web_port}"),
    Setting("RIDDLE_TAILNET", "tailnet", bool, False, "web",
            "Dev mode behind `tailscale serve`: hot reload has to dial 443 "
            "over wss, because tailscale terminates the TLS."),

    # --- safety ---
    Setting("RIDDLE_ALLOW_DRAW", "allow_draw", bool, False, "safety",
            "Standing permission to put ink on whatever page is open. Leave "
            "it unset and pass --yes per command instead."),
    Setting("RIDDLE_ALLOW_SNAP", "allow_snap", bool, False, "safety",
            "Standing permission to read the tablet's screen out of another "
            "process's memory. Same advice."),
)

BY_NAME = {s.name: s for s in SETTINGS}
SECTIONS = ("device", "diary", "hand", "voice", "web", "safety")
SECTION_TITLES = {
    "device": "device access",
    "diary": "the diary",
    "hand": "the hand",
    "voice": "the page you speak into",
    "web": "the client's build",
    "safety": "safety",
}


@dataclass(frozen=True)
class Config:
    ssh_host: str
    wifi_host: str
    agent: str
    notebook: str
    pause_ms: int
    openai_model: str
    openai_key: str
    openai_url: str
    max_words: int
    font_body: str
    font_accent: str
    ink_height: int
    pressure: int
    db: Path
    web_host: str
    web_port: int
    web_dir: Path
    web_debug: bool
    web_password: str
    asr_model: Path
    asr_threads: int
    vad_floor: float
    vad_hang_ms: int
    vad_max_ms: int
    audio_keep_days: int
    server: str
    tailnet: bool
    allow_draw: bool
    allow_snap: bool
    # where each value came from: "default" | ".env" | "env"
    sources: dict[str, str]


# --- reading .env -------------------------------------------------------


def read_dotenv(path: Path) -> dict[str, str]:
    """A dotenv reader in twenty lines, with no interpolation.

    `set -a; source .env` would expand $VAR. Nothing in this project's .env
    uses that, and silently interpolating half a password is worse than not
    supporting it at all.
    """
    if not path.is_file():
        return {}
    found: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):].lstrip()
        key, sep, value = line.partition("=")
        if not sep:
            continue
        key, value = key.strip(), value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        found[key] = value
    return found


def _coerce(setting: Setting, raw: str):
    if setting.kind is bool:
        return raw.strip().lower() in ("1", "true", "yes", "on")
    if setting.kind is Path:
        base = {"root": paths.ROOT, "var": paths.VAR, "models": paths.MODELS}
        return paths.under_root(raw, base[setting.base])
    return setting.kind(raw)


_CONFIG: Config | None = None


def load(env_file: Path | None = None, *, use_dotenv: bool = True) -> Config:
    """Build the configuration once, from .env and the environment."""
    global _CONFIG
    path = env_file or (paths.ROOT / ".env")
    dotenv = read_dotenv(path) if use_dotenv else {}

    values: dict[str, object] = {}
    sources: dict[str, str] = {}
    derived: list[Setting] = []
    for setting in SETTINGS:
        if setting.manual:
            continue
        if setting.name in os.environ:
            raw, where = os.environ[setting.name], "env"
        elif setting.name in dotenv:
            raw, where = dotenv[setting.name], ".env"
        elif setting.derive is not None:
            derived.append(setting)
            continue
        else:
            raw, where = None, "default"
        if raw is None:
            default = setting.default
            if setting.kind is Path and isinstance(default, str):
                default = _coerce(setting, default)
            values[setting.attr] = default
        else:
            values[setting.attr] = _coerce(setting, raw)
        sources[setting.name] = where

    # A derived setting is a function of the others, so the others are built
    # first and it reads them off a throwaway copy.
    partial = Config(**values, **{s.attr: "" for s in derived}, sources=sources)
    for setting in derived:
        values[setting.attr] = setting.derive(partial)
        sources[setting.name] = "derived"
    _CONFIG = Config(**values, sources=sources)
    return _CONFIG


def get() -> Config:
    """The loaded configuration. The CLI loads it before anything else runs."""
    if _CONFIG is None:
        return load()
    return _CONFIG


# --- printing itself ----------------------------------------------------


def as_example() -> str:
    """`.env.example`, generated.

    Every value is commented out at its code default. That is the whole
    trick: a template that sets nothing cannot drift from the code.
    """
    out = [
        "# Copy to .env and fill in what you want to change. .env is",
        "# gitignored and must never be committed: it holds the tablet's",
        "# root password.",
        "#",
        "# Generated by `riddle config --example`. Every line below is the",
        "# code's own default, commented out -- uncomment to override.",
    ]
    for section in SECTIONS:
        out.append("")
        out.append(f"# --- {SECTION_TITLES[section]} ---")
        for setting in SETTINGS:
            if setting.section != section:
                continue
            for line in _wrap(setting.help):
                out.append(f"# {line}")
            shown = setting.default
            if setting.derive is not None:
                shown = "<derived from RIDDLE_WEB_HOST and RIDDLE_WEB_PORT>"
            elif isinstance(shown, bool):
                shown = "1" if shown else ""
            out.append(f"# {setting.name}={shown if shown is not None else ''}")
            out.append("")
        out.pop()
    return "\n".join(out) + "\n"


def _wrap(text: str, width: int = 72) -> list[str]:
    words, lines, line = text.split(), [], ""
    for word in words:
        if line and len(line) + 1 + len(word) > width:
            lines.append(line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        lines.append(line)
    return lines


def check(env_file: Path | None = None) -> list[str]:
    """Everything wrong with the configuration, as sentences."""
    path = env_file or (paths.ROOT / ".env")
    problems: list[str] = []
    dotenv = read_dotenv(path)
    for key in dotenv:
        if key not in BY_NAME:
            problems.append(f"{path.name} sets {key}, which nothing reads")
    for name, raw in dotenv.items():
        setting = BY_NAME.get(name)
        if setting is None or setting.kind in (str, Path, bool):
            continue
        try:
            setting.kind(raw)
        except ValueError:
            problems.append(f"{name}={raw!r} is not a {setting.kind.__name__}")
    example = paths.ROOT / ".env.example"
    if example.is_file() and example.read_text() != as_example():
        problems.append(".env.example is stale: regenerate with `riddle config --example`")
    if path.is_file() and (path.stat().st_mode & 0o077):
        problems.append(f"{path.name} is readable by others; chmod 600 it")
    return problems
